def additoin(x, y):
    x = 10
    y = 20
try:
     
    result = x + b  
    print("The operation is successful")
    additoin(10, 20)


except NameError as e:
     print("an error occurred:", e)
except Exception as e:
     print(e)










     
   
     